- api-management-logger.tf
- api-management-policy-file-reader.tf
- api-management-product.tf
- api-management.tf
- data.tf
- demo.tfvars
- dev.tfvars
- ithc.tfvars
- main.tf
- resources/api-spec/hmi-api-health.json
- resources/policy-files/CaTH/api-op-publication-policy.xml
- resources/policy-files/HMI-Health-Check/api-op-health-check-policy.xml
- resources/policy-files/policies.json
- resources/policy-files/product-policy.xml
- sbox.tfvars
- stg.tfvars
- test.tfvars
- variables.tf
https://tools.hmcts.net/jira/browse/HMIS-1215
Setup terraform to deploy apim operations, implements request, response, tags for the operation and app insight. Also create health check endpoint for SDS HMI APIM.
[ ] Yes
[x] No
> HMIS-1215 Terraform setup

- api-management-logger.tf
- api-management-product.tf
- demo.tfvars
- dev.tfvars
- resources/policy-files/CaTH/api-op-publication-health-policy.xml
- resources/policy-files/CaTH/api-op-publication-policy.xml
- resources/policy-files/policies.json
- resources/policy-files/product-policy.xml
- sbox.tfvars
- stg.tfvars
- test.tfvars
- variables.tf
https://tools.hmcts.net/jira/browse/HMIS-1217
We need to add CaTH policy file to SDS APIM so that we can migrate CaTH to SDS APIM.
Read rate limit from environment file.
Log all failures (100%) in AppInsight
[ ] Yes
[x] No
> HMIS-1217 Add CaTH Policy files to SDS APIM

- data.tf
- ithc.tfvars
- main.tf
https://tools.hmcts.net/jira/browse/HMIS-1217
Fix deployment for SDS test
[ ] Yes
[x] No
> HMIS-1217 Fix deployment for SDS test

- infrastructure/main.tf
Change base url for endpoints
[ ] Yes
[x] No
> Change base url for endpoints

- infrastructure/main.tf
Revert base url change
[ ] Yes
[x] No
> Revert base url change

- Jenkinsfile_nightly
Updated cron timer for nightly
```
[ ] Yes
[x] No
```
> Updated cron timer for nightly

- Jenkinsfile_nightly
Updated nightly
```
[ ] Yes
[x] No
```
> Updated nightly

- .github/workflows/terraform_format.yml
- infrastructure/api-management-policy-file-reader.tf
- infrastructure/api-management-product.tf
- infrastructure/api-management.tf
- infrastructure/data.tf
- infrastructure/demo.tfvars
- infrastructure/dev.tfvars
- infrastructure/ithc.tfvars
- infrastructure/main.tf
- infrastructure/sbox.tfvars
- infrastructure/stg.tfvars
- infrastructure/test.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/HMIS-1247
Added new github workflow to automatically format terraform and commit to the branch.
```
[ ] Yes
[x] No
```
> HMIS-1247 Terraform format github action

- infrastructure/resources/policy-files/Video-Hearing/api-op-delete-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-cancel-hearing-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-clone-hearing-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-health-policy.xml
- infrastructure/resources/policy-files/policies.json
https://tools.hmcts.net/jira/browse/HMIS-1250
Add following remaining endpoints of Video hearing:
PATCH Cancel Hearing  - /hearings/{hearingId}/cancel
POST Clone Hearing - /hearings/{hearingId}/clone
DEL Delete Video Hearing - /resources/video-hearing/{hearingId}
GET Video Hearing Health - /vh-health
[ ] Yes
[x] No
> HMIS-1250 Migrate Video Hearing Endpoints Part3

- infrastructure/resources/policy-files/policies.json
https://tools.hmcts.net/jira/browse/HMIS-1250
In the latest documentation provided by VH, response code for cancel and clone endpoint will be 204.
[ ] Yes
[x] No
> Fix Video Hearing response code

- src/smokeTest/java/uk/gov/hmcts/reform/hmi/vh/HealthCheckSmokeTest.java
https://tools.hmcts.net/jira/browse/HMIS-1252
Added VH smoke test.
```
[ ] Yes
[x] No
```
> HMIS-1252 VH Smoke Tests

- config/owasp/suppressions.xml
- infrastructure/api-management-policy-file-reader.tf
- infrastructure/data.tf
- infrastructure/resources/policy-files/eLinks/api-op-get-people-by-id-elinks-policy.xml
- infrastructure/resources/policy-files/eLinks/api-op-get-people-by-params-elinks-policy.xml
- infrastructure/resources/policy-files/eLinks/api-op-update-people-elinks-policy.xml
- infrastructure/resources/policy-files/policies.json
https://tools.hmcts.net/jira/browse/HMIS-1258
Migrate eLink api endpoints
[ ] Yes
[x] No
> HMIS-1258 Migrate eLinks endpoints

- infrastructure/resources/policy-files/eLinks/api-op-elinks-health-policy.xml
- infrastructure/resources/policy-files/policies.json
https://tools.hmcts.net/jira/browse/HMIS-1260
Add health check endpoint for eLinks
[ ] Yes
[x] No
> HMIS-1260 Add health check endpoint for eLinks

- src/smokeTest/java/uk/gov/hmcts/reform/hmi/people/HealthCheckSmokeTest.java
https://tools.hmcts.net/jira/browse/HMIS-1260
Add smoke test for eLinks Api
[ ] Yes
[x] No
> HMIS-1206 Add smoke test for eLink Api

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/helper/RestClientHelper.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/people/PeopleTest.java
https://tools.hmcts.net/jira/browse/HMIS-1259
Add functional tests for Video Hearing.
[ ] Yes
[x] No
> HMIS-1259 Add functional tests for eLinks Api

- infrastructure/api-management-policy-file-reader.tf
- infrastructure/data.tf
- infrastructure/resources/policy-files/CFT/api-op-hmc-health-policy.xml
- infrastructure/resources/policy-files/Crime/api-op-crime-health-policy.xml
- infrastructure/resources/policy-files/SNL/api-op-snl-health-policy.xml
- infrastructure/resources/policy-files/eLinks/api-op-elinks-health-policy.xml
- infrastructure/resources/policy-files/policies.json
Create all health check endpoints need for APIM. 
[ ] Yes
[x] No
> Health check endpoints

- infrastructure/resources/policy-files/SNL/api-op-snl-health-policy.xml
Fix snl health check endpoint
[ ] Yes
[x] No
> Fix snl health check endpoint

- infrastructure/resources/policy-files/CFT/api-op-create-linked-hearing-group-policy.xml
- infrastructure/resources/policy-files/CFT/api-op-delete-hearing-policy.xml
- infrastructure/resources/policy-files/CFT/api-op-delete-linked-hearing-group-policy.xml
- infrastructure/resources/policy-files/CFT/api-op-request-direct-hearing-policy.xml
- infrastructure/resources/policy-files/policies.json
https://tools.hmcts.net/jira/browse/HMIS-1270
Migrate 4 endpoints which are being used by CFT.
[ ] Yes
[x] No
> HMIS-1270 CFT Migration Part 1

- infrastructure/resources/policy-files/CFT/api-op-get-reservations-policy.xml
- infrastructure/resources/policy-files/CFT/api-op-request-hearing-policy.xml
- infrastructure/resources/policy-files/CFT/api-op-update-linked-hearing-group-policy.xml
- infrastructure/resources/policy-files/policies.json
https://tools.hmcts.net/jira/browse/HMIS-1271
Migrate CFT Endpoints Part 2
[ ] Yes
[x] No
> HMIS-1271 Migrate CFT Endpoints Part 2

- src/smokeTest/java/uk/gov/hmcts/reform/hmi/cft/HealthCheckSmokeTest.java
https://tools.hmcts.net/jira/browse/HMIS-1271
Smoke Test for CFT
[ ] Yes
[x] No
> HMIS-1267 Smoke Test for CFT

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/direct/DirectHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/hearings/DeleteHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/helper/RestClientHelper.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/resources/CreateLinkHearingGroupTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/resources/DeleteLinkHearingGroupTest.java
https://tools.hmcts.net/jira/browse/HMIS-1288
Functional tests for CFT endpoints part 1
[ ] Yes
[x] No
> HMIS-1288 Functional tests for CFT endpoints part 1

- infrastructure/resources/policy-files/Crime/api-op-crime-health-policy.xml
> Updated crime cert in policy file

- src/smokeTest/java/uk/gov/hmcts/reform/hmi/crime/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/la/HealthCheckSmokeTest.java
https://tools.hmcts.net/jira/browse/HMIS-1275
Added remaining smoke tests for health check endpoints.
```
[ ] Yes
[x] No
```
> HMIS-1275 Smoke tests

- infrastructure/resources/policy-files/Hearings/api-op-update-hearing-policy.xml
https://tools.hmcts.net/jira/browse/HMIS-1272
Fixed the url
[ ] Yes
[x] No
> Fix the url

- infrastructure/resources/policy-files/policies.json
https://tools.hmcts.net/jira/browse/HMIS-1272
Fix endpoint path
[ ] Yes
[x] No
> Fix endpoint path

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/direct/PostDirectListingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/hearings/PutHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/schedules/PostScheduleTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/sessions/GetSessionsTest.java
https://tools.hmcts.net/jira/browse/HMIS-1274
Implement functional tests used by CFT/CRIME/SNL.
[ ] Yes
[x] No
> PUB-1274 Implement functional tests used by CFT/CRIME/SNL

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/PostCloneVideoHearingTest.java
Fix video hearing functional test
[ ] Yes
[x] No
> Fix Video hearing functional test

- config/owasp/suppressions.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-add-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-delete-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-edit-joh-policy.xml
- infrastructure/resources/policy-files/policies.json
https://tools.hmcts.net/jira/browse/HMIS-1246
Add new endpoints for Video hearing
[ ] Yes
[x] No
> HMIS-1246 Add new endpoints for Video hearing

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/DeleteJohVideoHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/PatchJohVideoHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/PostJohVideoHearingTest.java
- src/functionalTest/resources/vh/create-joh-video-hearing.json
- src/functionalTest/resources/vh/update-joh-video-hearing.json
https://tools.hmcts.net/jira/browse/HMIS-1246
Add Video Hearing functional tests
[ ] Yes
[x] No
> HMIS-1246 Add Video Hearing functional tests

- infrastructure/api-management-logger.tf
Headers information are not being logged for request, so it will fix it.
[ ] Yes
[x] No
> Fix App insight logging issue

- infrastructure/resources/policy-files/Video-Hearing/api-op-add-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-create-vh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-edit-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-update-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-groupid-hearing-policy.xml
- infrastructure/resources/policy-files/policies.json
https://tools.hmcts.net/jira/browse/HMIS-1245
Add video hearing version api 2 support
[ ] Yes
[x] No
> HMIS-1245 Add video hearing version 2 support

- infrastructure/resources/policy-files/Crime/api-op-crime-health-policy.xml
https://tools.hmcts.net/jira/browse/HMIS-1316
Add new crime health check endpoint
[ ] Yes
[x] No
> HMIS-1316 Add new crime health check endpoint

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/HMIS-1306
Fixing demo and ithc builds
[ ] Yes
[x] No
> HMIS-1306 Fixing demo and ithc builds

- infrastructure/main.tf
Removed MI data source as not being used.
> Removed MI not being used

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/direct/PostDirectListingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/direct/PutDirectHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/hearings/DeleteHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/hearings/HearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/hearings/PutHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/people/PeopleTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/pip/PostPublicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/reservations/GetReservationsTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/resources/DeleteLinkHearingGroupTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/resources/PostLinkHearingGroupTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/resources/PutLinkHearingGroupTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/schedules/PostScheduleTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/sessions/GetSessionsTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/DeleteJohVideoHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/DeleteParticipantTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/DeleteVideoHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/GetGroupIdTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/GetRetrieveVideoHearingsByUserTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/GetRetrieveVideoHearingsTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/PatchCancelVideoHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/PatchJohVideoHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/PostCloneVideoHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/PostJohVideoHearingTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/cft/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/crime/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/internal/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/la/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/people/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/pip/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/vh/HealthCheckSmokeTest.java
> Re-enabled tests

- infrastructure/prod.tfvars
> Setup prod

- infrastructure/demo.tfvars
- infrastructure/dev.tfvars
- infrastructure/ithc.tfvars
- infrastructure/prod.tfvars
- infrastructure/sbox.tfvars
- infrastructure/stg.tfvars
- infrastructure/test.tfvars
Fix crime health check endpoint
[ ] Yes
[x] No
> Fix crime health check endpoint

- infrastructure/resources/policy-files/Crime/api-op-crime-health-policy.xml
fix bug in crime health check endpoint
[ ] Yes
[x] No
> fix bug in crime health check endpoint

- config/owasp/suppressions.xml
> fixed build

- config/owasp/suppressions.xml
- infrastructure/api-management-logger-permission.tf
https://tools.hmcts.net/jira/browse/HMIS-1318
permission to sds apim
[ ] Yes
[x] No
> permission to sds apim

- infrastructure/api-management-logger-permission.tf
https://tools.hmcts.net/jira/browse/HMIS-1318
Fo not give access to prod logs
[ ] Yes
[x] No
> Fo not give access to prod logs

- build.gradle
- infrastructure/api-management-policy-file-reader.tf
- infrastructure/resources/policy-files/environments/demo.json
- infrastructure/resources/policy-files/environments/dev.json
- infrastructure/resources/policy-files/environments/ithc.json
- infrastructure/resources/policy-files/environments/prod.json
- infrastructure/resources/policy-files/environments/sbox.json
- infrastructure/resources/policy-files/environments/stg.json
- infrastructure/resources/policy-files/environments/test.json
https://tools.hmcts.net/jira/browse/HMIS-1329
Environment specific policy files
[ ] Yes
[x] No
> HMIS1329 Environment specific policy files

- infrastructure/api-management-logger-permission.tf
- infrastructure/data.tf
https://tools.hmcts.net/jira/browse/HMIS-1332
Add Monitoring Reader role to App Insights for non prod for the HMI Group
```
[ ] Yes
[x] No
```
> HMIS-1312 - Added app role

- infrastructure/api-management-logger-permission.tf
- infrastructure/data.tf
https://tools.hmcts.net/jira/browse/HMIS-1332
Updated permissions to App Insights
> HMI-1332 - Insights Permissions

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/hearings/HearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/pip/PostPublicationTest.java
- src/functionalTest/resources/hearings/update-hearing-request-payload.json
Fix the functional tests which are causing master pipeline to fail.
[ ] Yes
[x] No
> Fix functional tests

- infrastructure/resources/policy-files/api-policy.xml
https://tools.hmcts.net/jira/browse/HMIS-1338
Add DLRM as valid source and destination
[ ] Yes
[x] No
> HMIS-1338 Add DLRM as valid source and destination

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/helper/HeaderHelper.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/sessions/GetSessionsTest.java
Functional test to check whether we can use DLRM as valid source or not
[ ] Yes
[x] No
> Functional test for DLRM

- infrastructure/resources/policy-files/product-policy.xml
Fix rate limit for services using private dns
[ ] Yes
[x] No
> Fix rate limit for services using private dns

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/helper/HeaderHelper.java
Remove X-Forwarded header from functional tests
[ ] Yes
[x] No
> Remove X-Forwarded header from functional tests

- infrastructure/resources/policy-files/eLinks/api-op-elinks-health-policy.xml
- infrastructure/resources/policy-files/eLinks/api-op-get-people-by-id-elinks-policy.xml
- infrastructure/resources/policy-files/eLinks/api-op-get-people-by-params-elinks-policy.xml
- infrastructure/resources/policy-files/eLinks/api-op-update-people-elinks-policy.xml
https://tools.hmcts.net/jira/browse/PUB-2439
Update eLinks URL and Key
[ ] Yes
[x] No
> PUB-2439 Update eLinks URL and Key

- infrastructure/resources/policy-files/Hearings/api-op-update-hearing-policy.xml
Fix response for functional tests from LA.
[ ] Yes
[x] No
> Fix response for functional tests

- infrastructure/resources/policy-files/Hearings/api-op-update-hearing-policy.xml
Fix functional test LA response issue by adding EMULATOR
[ ] Yes
[x] No
> Fix functional test LA response issue by adding EMULATOR

- README.md
- infrastructure/resources/policy-files/eLinks/test/api-op-elinks-health-policy.xml
- infrastructure/resources/policy-files/eLinks/test/api-op-get-people-by-id-elinks-policy.xml
- infrastructure/resources/policy-files/eLinks/test/api-op-get-people-by-params-elinks-policy.xml
- infrastructure/resources/policy-files/eLinks/test/api-op-update-people-elinks-policy.xml
- infrastructure/resources/policy-files/environments/test.json
https://tools.hmcts.net/jira/browse/PUB-2452
Fix HMI Deployment Dependency by splitting the files which have changes specific to an environment. By default, it will pick the generic file.
[ ] Yes
[x] No
> PUB-2452 Fix HMI Deployment Dependency

- README.md
https://tools.hmcts.net/jira/browse/PUB-2400
Update the readme file for this project.
[ ] Yes
[x] No
> PUB-2400 Update Readme file

- infrastructure/resources/policy-files/CFT/api-op-hmc-health-policy.xml
- infrastructure/resources/policy-files/CaTH/api-op-publication-health-policy.xml
- infrastructure/resources/policy-files/CaTH/api-op-publication-policy.xml
- infrastructure/resources/policy-files/SNL/api-op-snl-health-policy.xml
https://tools.hmcts.net/jira/browse/PUB-2525
Add auth token caching for HMC health, SNL health and publication endpoints
```
[ ] Yes
[x] No
```
> PUB-2525 Add auth token caching

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/people/PeopleTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/people/HealthCheckSmokeTest.java
https://tools.hmcts.net/jira/browse/PUB-2541
eLinks moved to new infrastructure so we need to update the link credentials
[ ] Yes
[x] No
> PUB-2640 Fix eLinks API

- infrastructure/resources/policy-files/eLinks/api-op-elinks-health-policy.xml
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/people/PeopleTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/people/HealthCheckSmokeTest.java
https://tools.hmcts.net/jira/browse/PUB-2640
Fix bug and enable tests
[ ] Yes
[x] No
> PUB-2640 fix e links api url

- src/functionalTest/java/uk/gov/hmcts/reform/hmi/hearings/PutHearingTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/crime/HealthCheckSmokeTest.java
https://tools.hmcts.net/jira/browse/PUB-2629
Fix Crime Health check endpoint by installing new SSL certificate on SDS APIM.
[ ] Yes
[x] No
> PUB-2629 Fix Crime Health check endpoint

- infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-user-policy.xml
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/GetRetrieveVideoHearingsByUserTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/PostCloneVideoHearingTest.java
- src/functionalTest/resources/vh/create-vh-hearing.json
https://tools.hmcts.net/jira/browse/PUB-2680
Fix Video Hearing Functional Tests
[ ] Yes
[x] No
> PUB-2680 Fix Video Hearing Functional Tests

- infrastructure/api-management-policy-file-reader.tf
- infrastructure/api-management-policy-fragment.tf
- infrastructure/resources/policy-files/Video-Hearing/api-op-add-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-create-vh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-delete-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-delete-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-edit-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-user-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-update-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-add-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-cancel-hearing-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-clone-hearing-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-delete-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-edit-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-groupid-hearing-policy.xml
- infrastructure/resources/policy-fragments/failed-destination-authentication-response-fragment.xml
- infrastructure/resources/policy-fragments/invalid-destination-response-fragment.xml
- infrastructure/resources/policy-fragments/mock-generic-response-fragment.xml
- infrastructure/resources/policy-fragments/vh-auth-token-generation-fragment.xml
- infrastructure/resources/policy-fragments/vh-get-api-version-fragment.xml
https://tools.hmcts.net/jira/browse/PUB-2687
Add Policy Fragments for Video Hearing endpoints
[ ] Yes
[x] No
> PUB-2687 Video Hearing Policy Fragments

- infrastructure/api-management-policy-fragment.tf
- infrastructure/resources/policy-files/Video-Hearing/api-op-add-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-create-vh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-delete-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-delete-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-edit-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-user-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-update-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-add-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-cancel-hearing-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-clone-hearing-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-delete-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-edit-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-groupid-hearing-policy.xml
revert the fragment changes
```
[ ] Yes
[ ] No
```
> revert the fragment changes

- infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-id-policy.xml
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> Pub 2687 vh policy fragments

- infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-id-policy.xml
Reverts hmcts/hmi-apim-infrastructures#166
> Revert "Pub 2687 vh policy fragments"

- infrastructure/resources/policy-files/Video-Hearing/api-op-add-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-create-vh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-delete-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-delete-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-edit-participant-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-user-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-update-vh-by-id-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-add-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-cancel-hearing-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-clone-hearing-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-delete-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-edit-joh-policy.xml
- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-groupid-hearing-policy.xml
add the changes after testing
[ ] Yes
[x] No
> PUB-2678 add the changes

- infrastructure/resources/policy-files/Video-Hearing/api-op-vh-add-joh-policy.xml
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/PostCloneVideoHearingTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmi/vh/PostJohVideoHearingTest.java
https://tools.hmcts.net/jira/browse/PUB-2783
Implement v2 for AddJoh in Video Hearing
[ ] Yes
[x] No
> PUB-2783 Implement v2 for AddJoh in Video Hearing

- config/owasp/suppressions.xml
- infrastructure/api-management-policy-file-reader.tf
- infrastructure/resources/policy-files/HMI-Health-Check/api-op-auth-health-check-policy.xml
- infrastructure/resources/policy-files/api-policy.xml
- infrastructure/resources/policy-files/environments/demo.json
- infrastructure/resources/policy-files/environments/dev.json
- infrastructure/resources/policy-files/environments/ithc.json
- infrastructure/resources/policy-files/environments/prod.json
- infrastructure/resources/policy-files/environments/sbox.json
- infrastructure/resources/policy-files/environments/stg.json
- infrastructure/resources/policy-files/environments/test.json
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/cft/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/crime/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/helper/RestClientHelper.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/internal/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/la/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/people/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/pip/HealthCheckSmokeTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/hmi/vh/HealthCheckSmokeTest.java
https://tools.hmcts.net/jira/browse/PUB-2875
Implement private health check endpoint which can only be called if user provides the bearer token
[ ] Yes
[x] No
> PUB-2875 HMI Private Healthcheck Endpoint

- infrastructure/api-management-logger-permission.tf
https://tools.hmcts.net/jira/browse/PUB-2868
Create Group To Give SDS APIM Logs Permission
[ ] Yes
[x] No
> PUB-2868 Create Group To Give SDS APIM Logs Permission

- infrastructure/api-management-policy-file-reader.tf
- infrastructure/api-management.tf
- infrastructure/resources/policy-files/HMI-Health-Check/api-op-auth-health-check-policy.xml
https://tools.hmcts.net/jira/browse/PUB-2897
Fix Web Service URL and Private Health Check Endpoint
[ ] Yes
[x] No
> PUB-2897 Fix Web Service URL and Private Health Check Endpoint

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PUB-2953
Fix build
[ ] Yes
[x] No
> PUB-2953 Fix build

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- infrastructure/providers.tf
https://tools.hmcts.net/jira/browse/PUB-2959
Dependency Updates
```
[ ] Yes
[x] No
```
> PUB-2959 - Dependency Updates
